export default interface Character {
    [key: string]: string | number | null,
    id: string | null,
    name: string,
    accountId: string,
    specialty1: number,
    specialty2: number,
    aspectLevel: number,
    aspects1: number,
    aspects2: number,
    ancestryName: string,
    ancestryTrait: number,
    baseFitness: number,
    baseTechnique: number,
    baseFocus: number,
    baseSense: number,
    gold: number,
    silver: number,
    copper: number
}